# Deploy the project to GitHub Pages

name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Publish to Docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Copy files to deployment directory
        run: |
          mkdir -p deployment
          cp -r static deployment/
          cp -r src deployment/
          cp -r certs deployment/
          cp style.css deployment/
          cp index.html deployment/
          cp robots.txt deployment/
          cp sitemap.xml deployment/
          cp -r img deployment/
          cp -r languages deployment/
          rm -f deployment/README.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deployment